# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quenchforge < Formula
  desc "Patched ggml inference for AMD-Mac (chat, embed, rerank, transcribe)"
  homepage "https://github.com/Cerid-AI/quenchforge"
  version "0.6.2"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.6.2/quenchforge_0.6.2_darwin_amd64.tar.gz"
    sha256 "55ab6a54423df7f84a1eb3fbf33fce5e676e0ccd899e293da05ca30e9050cdc0"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.6.2/quenchforge_0.6.2_darwin_arm64.tar.gz"
    sha256 "5e4fb151a3313b2070e1e3d4d124667a29e6dd57f11cabe94bff22b680a622f3"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end

  service do
    run [opt_bin/"quenchforge", "serve"]
    keep_alive true
    log_path "#{var}/log/quenchforge/serve.log"
    error_log_path "#{var}/log/quenchforge/serve.err.log"
    working_dir var
    environment_variables QUENCHFORGE_LOG_DIR: "#{var}/log/quenchforge"
  end

  test do
    output = shell_output("#{bin}/quenchforge version")
    assert_match "quenchforge", output
    assert_match "darwin", output
    preflight_out = shell_output("#{bin}/quenchforge-preflight 2>&1")
    assert_match "status=", preflight_out
  end
end
