# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quenchforge < Formula
  desc "Patched ggml inference for AMD-Mac (chat, embed, rerank, transcribe)"
  homepage "https://github.com/Cerid-AI/quenchforge"
  version "0.9.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.9.0/quenchforge_0.9.0_darwin_amd64.tar.gz"
    sha256 "3cad7f0b688b697b6961156f756c762891f3b86a83e380baff8c8fe8a3c16448"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.9.0/quenchforge_0.9.0_darwin_arm64.tar.gz"
    sha256 "7911618e6896d7a7bad2f2085d4a7a42eb3ecb124f85e11f47b44008379dd8b1"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end

  service do
    run [opt_bin/"quenchforge", "serve"]
    keep_alive true
    log_path "#{var}/log/quenchforge/serve.log"
    error_log_path "#{var}/log/quenchforge/serve.err.log"
    working_dir var
    environment_variables QUENCHFORGE_LOG_DIR: "#{var}/log/quenchforge"
  end

  test do
    output = shell_output("#{bin}/quenchforge version")
    assert_match "quenchforge", output
    assert_match "darwin", output
    preflight_out = shell_output("#{bin}/quenchforge-preflight 2>&1")
    assert_match "status=", preflight_out
  end
end
