# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quenchforge < Formula
  desc "Patched ggml inference for AMD-Mac (chat, embed, rerank, transcribe)"
  homepage "https://github.com/Cerid-AI/quenchforge"
  version "0.5.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.5.1/quenchforge_0.5.1_darwin_amd64.tar.gz"
    sha256 "196e49c0c03accc70de325d01ab99cb3b0f2369363f30d7d460bf07412809db3"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Cerid-AI/quenchforge/releases/download/v0.5.1/quenchforge_0.5.1_darwin_arm64.tar.gz"
    sha256 "d810a9010e50e95350aa071b32a1c305137a2c9018ba9dcf635b9f4ca260264a"

    define_method(:install) do
      bin.install "quenchforge"
      bin.install "quenchforge-preflight"
      (var/"log/quenchforge").mkpath
    end
  end

  service do
    run [opt_bin/"quenchforge", "serve"]
    keep_alive true
    log_path "#{var}/log/quenchforge/serve.log"
    error_log_path "#{var}/log/quenchforge/serve.err.log"
    working_dir var
    environment_variables QUENCHFORGE_LOG_DIR: "#{var}/log/quenchforge"
  end

  test do
    output = shell_output("#{bin}/quenchforge version")
    assert_match "quenchforge", output
    assert_match "darwin", output
    preflight_out = shell_output("#{bin}/quenchforge-preflight 2>&1")
    assert_match "status=", preflight_out
  end
end
